securityDefinitions:
  basicAuth:
    type: basic
  Bearer:
    type: apiKey
    name: Authorization
    in: header
tags:
  - name: BootEnvs
  - name: Templates
  - name: Files
  - name: Interfaces
  - name: Isos
  - name: Subnets
  - name: Reservations
  - name: Prefs
  - name: Leases
  - name: Machines
  - name: Profiles
  - name: Users
  - name: Params
  - name: Tasks
  - name: Jobs
  - name: Plugins
  - name: PluginProviders
