securityDefinitions:
  basicAuth:
    type: basic
  Bearer:
    type: apiKey
    name: Authorization
    in: header
responses:
  FileResponse:
    description: FileResponse returned on a successful GET of a file
    schema:
      type: string
      format: binary
  JobLogResponse:
    description: JobLogResponse returned on a successful GET of a log
    schema:
      type: string
      format: binary
tags:
  - name: BootEnvs
  - name: Templates
  - name: Files
  - name: Interfaces
  - name: Isos
  - name: Subnets
  - name: Reservations
  - name: Prefs
  - name: Leases
  - name: Machines
  - name: Profiles
  - name: Users
  - name: Roles
  - name: Tenants
  - name: Params
  - name: Tasks
  - name: Jobs
  - name: Logs
  - name: Plugins
  - name: PluginProviders
  - name: Indexes
  - name: Contents
  - name: Events
  - name: Info
  - name: Stages
  - name: System
  - name: Workflows
  - name: Meta
